package org.horndevelopmentteam.bankingtransactionriskfraudmonitoring.audit;

public enum AuditEventType {
    CUSTOMER_CREATED,
    ACCOUNT_CREATED,
    TRANSACTION_CREATED,
    RISK_SCORE_GENERATED,
    FRAUD_ALERT_CREATED,
    ALERT_STATUS_UPDATED,
    CASE_CREATED,
    CASE_UPDATED,
    CASE_DECISION_UPDATED,
    DATA_INGESTION_STARTED,
    DATA_INGESTION_COMPLETED,
    DATA_QUALITY_CHECK_COMPLETED,
    PIPELINE_FAILED,
    ML_SCORE_REQUESTED,
    ML_SCORE_COMPLETED,
    ML_SCORE_FAILED,
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_PASSWORD_RESET,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    TEST_TRANSACTION_CREATED,
    TEST_TRANSACTION_RISK_SCORED,
    TEST_TRANSACTION_ALERT_GENERATED
}
